FLAGS = -Wall -Wextra -Werror -pedantic

# Target for programming challenge 19
# Date completed: 4-14-2014
pc19: pc19.cpp SLNode.cpp SLNode.h SList.cpp SList.h
	g++ $(FLAGS) SLNode.cpp SList.cpp pc19.cpp -o pc19