FLAGS = -Wall -Wextra -Werror -pedantic

# Target for programming challenge 17
# Date completed: 4-9-2014
pc17: pc17.cpp SLNode.cpp SLNode.h
	g++ $(FLAGS) SLNode.cpp pc17.cpp -o pc17

# Target for programming challenge 18
# Date completed: 4-9-2014
pc18: pc18.cpp SLNode.cpp SLNode.h SList.cpp SList.h
	g++ $(FLAGS) SLNode.cpp SList.cpp pc18.cpp -o pc18