FLAGS = -Wall -Wextra -Werror -pedantic -Wno-newline-eof

# Target for programming challenge 18
# Date completed: 4-9-2014
pc18: pc18.cpp SLNode.cpp SLNode.h SList.cpp SList.h
	g++ $(FLAGS) SLNode.cpp SList.cpp pc18.cpp -o pc18