FLAGS = -Wall -Wextra -Werror -pedantic -Wno-newline-eof

# Target for programming challenge 26
# Date completed: 5-7-2014
pc26: pc26.cpp bstree.h bstree.cpp BSTNode.h BSTNode.cpp
	g++ $(FLAGS) bstree.cpp BSTNode.cpp pc26.cpp -o pc26