FLAGS = -Wall -Wextra -Werror -pedantic -Wno-newline-eof

# Target for programming challenge 28
# Date completed: 5-19-2014
pc29: pc29.cpp treasurechest.h treasurechest.cpp
	g++ $(FLAGS) treasurechest.cpp pc29.cpp -o pc29