FLAGS = -Wall -Wextra -Werror -pedantic -Wno-newline-eof

# Target for programming challenge 27
# Date completed: 5-12-2014
pc27: pc27.cpp bstree.h bstree.cpp BSTNode.h BSTNode.cpp
	g++ $(FLAGS) bstree.cpp BSTNode.cpp pc27.cpp -o pc27