FLAGS = -Wall -Wextra -Werror -pedantic -Wno-newline-eof

# Target for programming challenge 28
# Date completed: 5-19-2014
pc28: pc28.cpp item.h item.cpp fooditem.h fooditem.cpp magicitem.h magicitem.cpp
	g++ $(FLAGS) item.cpp fooditem.cpp magicitem.cpp pc28.cpp -o pc28