FLAGS = -Wall -Wextra -Werror -pedantic -Wno-newline-eof

# Target for programming challenge 25
# Date completed: 5-5-2014
pc25: pc25.cpp BSTNode.h BSTNode.cpp
	g++ $(FLAGS) BSTNode.cpp pc25.cpp -o pc25