FLAGS = -Wall -Wextra -Werror -pedantic -Wno-newline-eof

# Target for programming challenge 20
# Date completed: 4-16-2014
pc20: pc20.cpp SLNode.cpp SLNode.h SList.cpp SList.h
	g++ $(FLAGS) SLNode.cpp SList.cpp pc20.cpp -o pc20